#ifndef __CONSTANTS__H__
#define __CONSTANTS__H__

//Général
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720


//Joueur
#define PLAYER_INIT_WIDTH 32
#define PLAYER_INIT_HEIGHT 32

#define PLAYER_INIT_SPEED 5
#define PLAYER_MAX_SPEED 25
#define PLAYER_COLLIDE_IDFRAME 120

#define PLAYER_INIT_HEALTH 3
#define PLAYER_MAX_BULLETS 1000

//Bullets
#define BULLET_INIT_WIDTH 20
#define BULLET_INIT_HEIGHT 20

#define BULLET_INIT_SPEED 10
#define BULLET_MAX_SPEED 30

//Ennemy
#define ENNEMY_INIT_WIDTH 32
#define ENNEMY_INIT_HEIGHT 32
#define NB_ENNEMIES 3

//Map
#define MAP_SIZE 6
#define GATE_WIDTH 100
#define GATE_HEIGHT 20

#endif